spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:h2:mem:inventorydb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

resilience4j:
  circuitbreaker:
    instances:
      inventoryCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      inventoryRetry:
        maxAttempts: 3
        waitDuration: 1s
  ratelimiter:
    instances:
      orderRateLimiter:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 0

security:
  jwt:
    secret: very-secret-key-change-in-prod
    expirationMs: 3600000

server:
  port: 8081
